### ISSUE TITLE
リアクション内でのスタンプの順番

### ISSUE THREAD

**Issue by g0rityu** [schmelzen02/tamakibot#16]
右クリックー>リアクションでスタンプの状況を確認できると思うのですが、スタンプの表示順が「そのスタンプを押した人数」の降順になっているのでぱっと見わかりにくい。
実装できるなら「1->1.5->2->2.5」といった感じで固定していただけると見やすいかと(個人的意見)

**Comment by schmelzen02** [comment]
早速ありがとうございます！

リアクションの詳細確認はbotではなくDIscord自体の機能の為、修正することができません。。
(他のリアクションも同じ表示になるはず)
